In [1]:
import numpy as np #used for matrixces
a=np.array([1,2,3,4])


In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape #how many rows and number of elements

(4,)

In [18]:
b=np.array([(1,2,3),(4,5,6)])

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
type(b)

numpy.ndarray

In [22]:
b.shape

(2, 3)

In [23]:
a.max()

4

In [24]:
b.min()

1

In [25]:
a.prod()

24

In [29]:
b.resize(3,2)

AttributeError: 'list' object has no attribute 'resize'

In [28]:
b=b.reshape(4,2)

AttributeError: 'list' object has no attribute 'reshape'

In [31]:
c=np.array([(1,2,3,4),(4,5,6,7)])

In [32]:
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [33]:
c.sum(axis=1) #col sum

array([10, 22])

In [35]:
c.sum(axis=0) #row sum

array([ 5,  7,  9, 11])

In [39]:
import pandas as pd
df=pd.DataFrame({'col1':['A','B','B','A'],'col2':[1,2,2,3]})

In [40]:
df

col1  col2
0    A     1
1    B     2
2    B     2
3    A     3

In [42]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [43]:
df[df.duplicated()]

col1  col2
2    B     2

In [44]:
df1=df.drop_duplicates()

In [45]:
df1

col1  col2
0    A     1
1    B     2
3    A     3

In [46]:
df2=df1.reset_index()

In [47]:
df2

index col1  col2
0      0    A     1
1      1    B     2
2      3    A     3

In [48]:
df3=df2.drop('index',axis=1)

In [49]:
df3

col1  col2
0    A     1
1    B     2
2    A     3